location /extras/ai-usage/push/ {
    auth_request off;
    proxy_pass http://kvm_ai_usage/push/;
    include /etc/kvmd/nginx/loc-proxy.conf;
    include /etc/kvmd/nginx/loc-nocache.conf;
}

location /extras/ai-usage/ {
    proxy_pass http://kvm_ai_usage/;
    include /etc/kvmd/nginx/loc-proxy.conf;
    include /etc/kvmd/nginx/loc-login.conf;
    include /etc/kvmd/nginx/loc-nocache.conf;
}
